version: '3.8'

services:
  server_dev:
    build:
      context: ./scraping-system
      dockerfile: local.Dockerfile
    ports:
      - 3000:3000
      - 9234:9234 # For VS Code debugger
    depends_on:
      - mongo
    volumes:
      - ./scraping-system:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
