version: '3.8'

services:
  server_prod:
    build:
      context: ./scraping-system
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9234:9234 # For VS Code debugger
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
